from_latest_tag = false
ignore_merge_commits = false
branch_whitelist = [
  "main",
  "release/**"
]
pre_bump_hooks = [
    "cargo set-version {{version}}",
    "cargo build --release",
]
post_bump_hooks = [
    "git push origin {{version}}",
]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "just-one-init"
owner = "PurpleBooth"
authors = []

[bump_profiles]
